import json
import uuid
import re
from google import genai
from google.genai import types
from app.common.config import settings
from app.common.database import SessionLocal
from app.models.article import Article
from app.models.audit import SiteSetting

class AINewsService:
    def __init__(self):
        pass

    async def generate_and_publish_news(self, category_id: str, author_id: str) -> dict:
        db = SessionLocal()
        try:
            # 1. Fetch API Key from DB or fallback to env
            api_key_setting = db.query(SiteSetting).filter(SiteSetting.key == 'GEMINI_API_KEY').first()
            api_key = api_key_setting.value_json if api_key_setting else settings.AI_API_KEY
            
            if not api_key:
                raise ValueError("Google AI API Key is not configured in Settings or Env. Cannot generate news.")
            
            client = genai.Client(api_key=api_key)
            model_name = settings.AI_MODEL_NAME or 'gemini-1.5-flash'
        
        prompt = """
        You are an expert technology journalist for 'CamTech Blog'. 
        Search for today's top global technology news or breakthrough.
        Write a professional, engaging news article about it.
        Return the result strictly as a JSON object with the following keys:
        - title: The headline of the article
        - summary: A short 1-2 sentence summary
        - content: The full article body in Markdown format
        - source_url: A relevant source URL if available, or 'https://news.google.com'
        """
        
        # We use Google Search grounding if supported, but here we just ask the model.
        # Since it's Gemini 1.5, it can generate great tech news.
        response = client.models.generate_content(
            model=model_name,
            contents=prompt,
            config=types.GenerateContentConfig(
                temperature=0.7,
                response_mime_type="application/json"
            )
        )
        
        try:
            data = json.loads(response.text)
        except json.JSONDecodeError:
            # Fallback regex extraction if model wraps in ```json
            match = re.search(r'```(?:json)?\n(.*?)\n```', response.text, re.DOTALL)
            if match:
                data = json.loads(match.group(1))
            else:
                raise ValueError("Failed to parse JSON from AI response")

        # Generate unique slug
        base_slug = re.sub(r'[^a-z0-9]+', '-', data['title'].lower()).strip('-')
        slug = f"{base_slug}-{uuid.uuid4().hex[:4]}"

        # Save to database
        try:
            new_article = Article(
                title=data['title'],
                slug=slug,
                summary=data['summary'],
                content=data['content'],
                country='WORLD',
                primary_source_url=data.get('source_url', 'https://camtech.cam'),
                category_id=category_id,
                author_id=author_id,
                status='PUBLISHED',
                language='en',
                source_attribution_text='Generated by Google AI'
            )
            db.add(new_article)
            db.commit()
            db.refresh(new_article)
            
            return {
                "id": new_article.id,
                "title": new_article.title,
                "slug": new_article.slug,
                "status": "success"
            }
        except Exception as e:
            db.rollback()
            raise e
        finally:
            db.close()

ai_news_service = AINewsService()
