name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Auto Deploy
    runs-on: self-hosted

    steps:
      - name: Deploy on Server
        run: |
          cd /home/ubuntu-server/CamTech.Blog
          git reset --hard HEAD
          git pull origin main
          docker compose down --remove-orphans
          docker compose up --build -d
          
      - name: Seed Database
        run: |
          cd /home/ubuntu-server/CamTech.Blog
          # We check if the api container is running and seed data
          docker compose exec -T api python seed_data.py || echo "Seed failed or not applicable"
